apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APP_NAME
  template:
    metadata:
      labels:
        app: APP_NAME
    spec:
      containers:
      - name: APP_NAME
        image: REGISTRY_NAME.azurecr.io/IMAGE_NAME:v1
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: configfile
            mountPath: /code/config.py
            subPath: config.py
      volumes:
        - name: configfile
          secret:
            secretName: SECRET_NAME
            items:
              - key: config
                path: config.py
---
apiVersion: v1
kind: Service
metadata:
  name: APP_NAME
spec:
  loadBalancerIP: IP_ADDRESS
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: APP_NAME

