jobs:

- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip 
    displayName: 'Install dependencies'

  - script: |
      pip install pytest
      cd examples/notebooks
      pytest utilities-test.py --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'pytest'      

  - script: |
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ~/miniconda.sh  
      bash ~/miniconda.sh -b -p $HOME/miniconda

      export PATH="$HOME/miniconda/bin:$PATH"
      source $HOME/miniconda/bin/activate

      cd examples/notebooks/xDeepFM && ./run_notebooks.sh

    condition: eq(variables['Agent.OS'], 'Darwin')
    displayName: 'Install miniconda - Darwin'

  - script: |
      wget https://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O ~/miniconda.sh  
      bash ~/miniconda.sh -b -p $HOME/miniconda

      export PATH="$HOME/miniconda/bin:$PATH"
      source $HOME/miniconda/bin/activate

      cd examples/notebooks/xDeepFM && ./run_notebooks.sh
      
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: 'Install miniconda - Linux'

  - script: |
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe -O ~/miniconda.exe  
      start /wait "" Miniconda4-latest-Windows-x86_64.exe /InstallationType=JustMe /RegisterPython=0 /S /D=%UserProfile%\Miniconda3       
    condition: eq(variables['Agent.OS'], 'Windows_NT')
    displayName: 'Install miniconda - Windows'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()
