jobs:

- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
 
  -  bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
     displayName: Add conda to PATH

  -  bash: ./scripts/generate_conda_file.sh
     displayName: generate yaml
    
  -  bash: conda create --yes --quiet --name Recommender -f conda_bare.yaml python=3.6
     displayName: Create Anaconda environment

  - bash: |
      source activate Recommender
      pip install pytest
 
      cd tests/unit
      python -m pytest -m "notebooks and not spark" --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'Unit tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()
