jobs:

- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip && pip install pytest papermill
    displayName: 'Install dependencies'

  - script: |
      ./scripts/generate_conda_file.sh
    displayName: 'Create conda environment.yml'

  - task: CondaEnvironment@1
    inputs:
      environmentName: Recommender
      packageSpecs: 'python=3'
      createOptions: '-f conda_bare.yml'
      updateConda: true

  - script: |
      cd tests/unit
      pytest -m "notebooks and not spark" --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'Unit Tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()