jobs:

- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
 
  - task: CondaEnvironment@1
    inputs:
      createCustomEnvironment: true
      environmentName: Recommender
      packageSpecs: 'python=3.6'
      updateConda: true

  - script: sudo install -d -m 0777 /usr/local/miniconda/envs
    displayName: Fix Conda permissions

  - script: sudo install -d -m 0777 /usr/envs
    condition: eq(variables('Agent.OS'), 'Linux')
    displayName: Fix Conda permissions (Linux)
      sudo install -d -m 0777 /usr/envs/Recommender

  - script: |
      ./scripts/generate_conda_file.sh
      # sudo conda env update -n Recommender -f conda_bare.yaml
      conda env update -f conda_bare.yaml

      pip install pytest
 
      cd tests/unit
      python -m pytest -m "notebooks and not spark" --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'Unit tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()
