name: Update Documentation

on:
  push:
    branches:
      - miguel/jupyter_book

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r docs/requirements-doc.txt

      - name: Build and deploy documentation
        run: |
          jupyter-book build docs
          cd docs
          git add .
          git commit -m "Update documentation"
          git push origin gh-pages
