name: Update Documentation

on:
  push:
    branches:
      - miguel/jupyter_book

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install --no-use-pep517 lightfm
          pip install .
          pip install -r docs/requirements-doc.txt

      - name: Build documentation
        run: |
          jupyter-book build docs

      - name: Deploy documentation
        run: |
          cd docs/_build/html
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git config user.signingkey "${{ secrets.GPG_KEY_ID }}"
          git add * -f
          git commit -m "Update documentation"
          git push origin gh-pages
